// app/src/pages/LoginPage.tsx
import * as yup from "yup";
import { useForm, Controller } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import logo from "../../public/logo/logo-900.svg";
import { Link } from "react-router-dom";
function LoginPage() {
    type Person = {
        username: string;
        password: string;
    };

    const schema: yup.ObjectSchema<Person> = yup.object().shape({
        username: yup.string().required(),
        password: yup.string().required(),
    });

    const defaultValues: Person = {
        username: "",
        password: "",
    };

    const {
        control,
        handleSubmit,
        formState: { errors },
    } = useForm<Person>({
        defaultValues,
        mode: "onBlur",
        resolver: yupResolver(schema),
    });

    // const auth = useAuth()

    const onSubmit = (data: Person) => {
        console.log(data);
        // const { username, password } = data
        // auth.login({ email, password}, () => {
        //   setError('email', {
        //     type: 'manual',
        //     message: 'Email or Password is invalid'
        //   })
        // })
    };

    return (
        <div className="h-screen flex justify-center items-center relative">
            <div className="h-screen w-screen overlay-background absolute top-0 left-0 -z-10"></div>
            <form
                noValidate
                autoComplete="off"
                onSubmit={handleSubmit(onSubmit)}
            >
                <div className="bg-white/90 px-16 py-10 rounded-lg shadow flex flex-col">
                    <div className="flex flex-col justify-center items-center gap-2 mb-8">
                        <img src={logo} className="w-16 h-16"></img>
                        <div className="font-bold text-xl">HermesCS</div>
                    </div>
                    <div className="mb-4">
                        <Controller
                            name="username"
                            control={control}
                            rules={{ required: true }}
                            render={({
                                field: { value, onChange, onBlur },
                            }) => (
                                <input
                                    type="text"
                                    className="px-4 py-2 rounded-lg border"
                                    id="login-username"
                                    value={value}
                                    onBlur={onBlur}
                                    onChange={onChange}
                                    placeholder="Username"
                                />
                            )}
                        />
                        {errors.username && (
                            <p className="text-red-500 text-sm">
                                {errors.username.message}
                            </p>
                        )}

                        {/* <input type="text" className="px-4 py-2 rounded-lg border" placeholder="Username"></input> */}
                    </div>
                    <div className="mb-4">
                        <Controller
                            name="password"
                            control={control}
                            rules={{ required: true }}
                            render={({
                                field: { value, onChange, onBlur },
                            }) => (
                                <input
                                    className="px-4 py-2 rounded-lg border"
                                    id="login-password"
                                    type="password"
                                    value={value}
                                    onBlur={onBlur}
                                    onChange={onChange}
                                    placeholder="Password"
                                />
                            )}
                        />
                        {errors.password && (
                            <p className="text-red-500 text-sm">
                                {errors.password.message}
                            </p>
                        )}
                        {/* <input type="password" className="px-4 py-2 rounded-lg border" placeholder="Password"></input> */}
                    </div>
                    <div className="my-6 relative">
                        <button
                            type="submit"
                            className="w-full px-4 py-2 rounded-lg bg-blue-500 text-white font-semibold"
                        >
                            Login
                        </button>
                    </div>
                    <Link to={"/signup"} className="flex justify-center">
                        <button className="tex-sm">Sign up</button>
                    </Link>
                </div>
            </form>
        </div>
    );
}

export default LoginPage;

// app-ng/src/app/features/auth/pages/login-page/login-page.component.ts
import { Component } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthorizationService } from 'src/app/service/authorization.service';

@Component({
  selector: 'app-login-page',
  templateUrl: './login-page.component.html',
  styleUrls: ['./login-page.component.scss'],
})
export class LoginPageComponent {
  loginForm = this.fb.group({
    username: ['', Validators.required],
    password: ['', Validators.required],
  });

  constructor(
    private fb: FormBuilder,
    private authService: AuthorizationService,
    private router: Router
  ) {}

  login() {
    let username = this.loginForm.value.username;
    let password = this.loginForm.value.password;
    if (username && password && username.length && password.length) {
      this.authService.login(
        this.loginForm.value.username!,
        this.loginForm.value.password!
      ).subscribe(res => {
        this.router.navigate(['/']);
      });
    }
  }
}

<div class="h-screen flex justify-center items-center relative">
  <div
    class="h-screen w-screen overlay-background absolute top-0 left-0 -z-10"
  ></div>
  <form [formGroup]="loginForm" (submit)="login()">
    <div class="bg-white/90 px-16 py-10 rounded-lg shadow flex flex-col">
      <div class="flex flex-col justify-center items-center gap-2 mb-8">
        <img src="assets/logo/logo-900.svg" class="w-16 h-16" />
        <div class="font-bold text-xl">HermesCS</div>
      </div>
      <div class="mb-4">
        <input
          type="text"
          formControlName="username"
          class="px-4 py-2 rounded-lg border"
          placeholder="Username"
        />
      </div>
      <div class="mb-4">
        <input
          type="password"
          formControlName="password"
          class="px-4 py-2 rounded-lg border"
          placeholder="Password"
        />
      </div>
      <div class="my-6 relative">
        <button
          type="submit"
          class="w-full px-4 py-2 rounded-lg bg-blue-500 text-white font-semibold"
        >
          Login
        </button>
      </div>
      <button routerLink="/auth/register" class="tex-sm">Sign up</button>
    </div>
  </form>
</div>
