// app-ng/src/app/features/chat/components/connector-filter/connector-filter.component.ts
import { Component } from '@angular/core';
import { ChatType } from 'src/app/models/chat';

@Component({
  selector: 'ConnectorFilter',
  templateUrl: './connector-filter.component.html',
  styleUrls: ['./connector-filter.component.scss'],
})
export class ConnectorFilterComponent {
  filter: ChatType | null = null;

  get ChatType() {
    return ChatType
  }

  changeFilter(filter: ChatType | null) {
    this.filter = filter;
  }
}

<div class="flex gap-3">
  <button
      class="px-4 py-2 rounded-full text-sm font-semibold hover:bg-gray-50"
      [ngClass]="{'bg-blue-100 text-blue-600': filter === null}"
      (click)="changeFilter(null)"
  >
      All
  </button>
  <button
      class="px-4 py-2 rounded-full text-sm font-semibold hover:bg-gray-50"
      [ngClass]="{'bg-blue-100 text-blue-600': filter === ChatType.PRIVATE}"
      (click)="changeFilter(ChatType.PRIVATE)"
  >
      Private
  </button>
  <button
      class="px-4 py-2 rounded-full text-sm font-semibold hover:bg-gray-50"
      [ngClass]="{'bg-blue-100 text-blue-600': filter === ChatType.GROUP}"
      (click)="changeFilter(ChatType.GROUP)"
  >
      Group
  </button>
</div>

// app/src/layout/Sidebar/ChatContactFilter/ConnectorFilter.tsx
import { useState } from "react";
import { ChatType } from "../../../models/chat";

interface ConnectorFilterProps {
    filterEmitter: (filter: ChatType | null) => void;
}

function ConnectorFilter({ filterEmitter }: ConnectorFilterProps) {
    const [filter, setFilter] = useState<ChatType | null>(null);

    const handleFilter = (newFilter: ChatType | null) => {
        setFilter(newFilter);
        filterEmitter(newFilter);
    };

    return (
        <div className="flex gap-3">
            <button
                className={`px-4 py-2 rounded-full  text-sm font-semibold hover:bg-gray-50 ${
                    filter === null && "bg-blue-100 text-blue-600"
                }`}
                onClick={() => handleFilter(null)}
            >
                All
            </button>
            <button
                className={`px-4 py-2 rounded-full  text-sm font-semibold hover:bg-gray-50 ${
                    filter === ChatType.PRIVATE && "bg-blue-100 text-blue-600"
                }`}
                onClick={() => handleFilter(ChatType.PRIVATE)}
            >
                Private
            </button>
            <button
                className={`px-4 py-2 rounded-full  text-sm font-semibold hover:bg-gray-50 ${
                    filter === ChatType.GROUP && "bg-blue-100 text-blue-600"
                }`}
                onClick={() => handleFilter(ChatType.GROUP)}
            >
                Group
            </button>
        </div>
    );
}

export default ConnectorFilter;
