// app-ng/src/app/features/chat/components/chat-box/chat-box.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { switchMap } from 'rxjs';
import { Message } from 'src/app/models/message';
import { AuthorizationService } from 'src/app/service/authorization.service';
import { ChatService } from 'src/app/service/chat.service';
@Component({
  selector: 'ChatBox',
  templateUrl: './chat-box.component.html',
  styleUrls: ['./chat-box.component.scss'],
})
export class ChatBoxComponent {
  messages: Message[] = [];
  myId: string = '';

  constructor(
    private route: ActivatedRoute,
    private chatService: ChatService,
    private auth: AuthorizationService
  ) {}

  ngOnInit() {
    this.myId = this.auth.myId;
    this.route.paramMap
      .pipe(
        switchMap((params) => {
          let chatId = params.get('chatId') || '';
          return this.chatService.getMessages(chatId);
        })
      )
      .subscribe();

      this.chatService.messages$.subscribe(messages => this.messages = messages)
  }
}

<div class="flex items-end relative h-full">
  <div class="flex grow flex-col-reverse gap-4 overflow-y-auto p-4 max-h-full">
          <Message
          *ngFor="let message of messages"
              [isSelf]="message.senderID === myId"
              [msg]="message"
          />
  </div>
</div>

// app/src/layout/ChatInterface/ChatBox/ChatBox.tsx
import { ChatHistory } from "../../../models/chat-history";
import Message from "../../../components/Message";
import { mockMe } from "../../../mockData";
import { useEffect, useState } from "react";
import { ResponseMessageContext } from "../../../models/message-context";

interface ChatBoxProps {
    data: ChatHistory[];
    sendToChatBox: ResponseMessageContext | null;
}

function ChatBox({ data, sendToChatBox }: ChatBoxProps) {
    const [chatMessages, setChatMessages] = useState(data);

    useEffect(() => {
        if (sendToChatBox) {
            setChatMessages((c) => [
                {
                    chatId: sendToChatBox.chatId,
                    messageId: sendToChatBox.messageId,
                    sender: sendToChatBox.sender,
                    timestamp: sendToChatBox.timestamp,
                    chatContent: sendToChatBox.chatContent,
                } as ChatHistory,
                ...c,
            ]);
        }
    }, [sendToChatBox]);

    useEffect(() => {
        setChatMessages(data);
    }, [data]);

    return (
        <div className="flex items-end relative h-full">
            <div className="flex grow flex-col-reverse gap-4 overflow-y-auto p-4 max-h-full">
                {chatMessages.map((msg) => (
                    <Message
                        key={msg.messageId}
                        isSelf={msg.sender === mockMe._id}
                        msg={msg}
                    />
                ))}
            </div>
        </div>
    );
}

export default ChatBox;
