// app-ng/src/app/features/chat/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { ChatType } from 'src/app/models/chat';
import { ChatContact } from 'src/app/models/chat-contact';
import { ChatService } from 'src/app/service/chat.service';

@Component({
  selector: 'Sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss'],
})
export class SidebarComponent {
  chatContacts: ChatContact[] = [];

  filteredChatContacts: ChatContact[] = [];
  isMainSettingsOpen = false;

  constructor(private chatService: ChatService) {}

  ngOnInit() {
    this.chatService.chatContacts$.subscribe({
      next: (res) => {
        this.chatContacts = res;
        this.filteredChatContacts = res;
      },
    });
  }

  onOpenMainSettings() {
    this.isMainSettingsOpen = true;
  }

  onCloseMainSettings() {
    this.isMainSettingsOpen = false;
  }

  onChangeFilter(filter: ChatType | null) {
    if (!filter) {
      this.filteredChatContacts = this.chatContacts;
    } else {
      if (filter === ChatType.PRIVATE) {
        this.filteredChatContacts = this.chatContacts.filter(
          (contact) => contact.type === ChatType.PRIVATE
        );
      } else {
        this.filteredChatContacts = this.chatContacts.filter(
          (contact) => contact.type === ChatType.GROUP
        );
      }
    }
  }
}

<div class="grow-0 shrink-0 w-96 h-screen border-r relative">
  <div>
      <div class="flex items-center justify-between px-6 py-3">
          <Brand />
          <AddConnector />
      </div>
      <div class="px-6 py-3">
          <div class="mb-3">
              <SearchBar />
          </div>
          <!-- <ConnectorFilter filterEmitter={filterChat} /> -->
          <ConnectorFilter (onChangeFilter)="onChangeFilter($event)" />
      </div>
      <div
          class="overflow-y-auto"
          style="height: calc( 100vh - 256px )"
      >
          <ChatContactList [chatContacts]="filteredChatContacts" />
      </div>
  </div>
  <MainSettings
      [openStatus]="isMainSettingsOpen"
      (onCloseMainSettings)="onCloseMainSettings()"
  />
  <OwnerPanel (onOpenMainSettings)="onOpenMainSettings()" />
</div>

// app/src/layout/Sidebar/Sidebar.tsx
import { useState } from "react";
import Brand from "./Brand/Brand";
import ChatContactList from "./ChatContact/ChatContactList";
import SearchBar from "./Searchbar/Searchbar";
import ConnectorFilter from "./ChatContactFilter/ConnectorFilter";
import MainSettings from "./MainSettings/MainSettings";
import OwnerPanel from "./OwnerPanel/OwnerPanel";
import AddConnector from "./AddConnector/AddConnector";
import { useLoaderData } from "react-router-dom";
import { ChatContact } from "../../models/chat-contact";
import { ChatType } from "../../models/chat";

function Sidebar() {
    const [isMainSettingsOpen, setIsMainSettingsOpen] = useState(false);
    const loadedChats = useLoaderData() as ChatContact[];

    const [chats, setChats] = useState(loadedChats);

    const filterChat = (filter: ChatType | null) => {
        setChats(
            filter !== null
                ? loadedChats.filter((chat) => chat.type === filter)
                : loadedChats
        );
    };

    const openMainSettings = () => {
        setIsMainSettingsOpen(!isMainSettingsOpen);
    };
    const closeMainSettings = () => {
        setIsMainSettingsOpen(!isMainSettingsOpen);
    };

    return (
        <div className="grow-0 shrink-0 w-96 h-screen border-r relative">
            <div>
                <div className="flex items-center justify-between px-6 py-3">
                    <Brand />
                    <AddConnector />
                </div>
                <div className="px-6 py-3">
                    <div className="mb-3">
                        <SearchBar />
                    </div>
                    <ConnectorFilter filterEmitter={filterChat} />
                </div>
                <div
                    className="overflow-y-auto"
                    style={{ height: "calc( 100vh - 256px )" }}
                >
                    <ChatContactList chats={chats} />
                </div>
            </div>
            <MainSettings
                openStatus={isMainSettingsOpen}
                emitCloseEvent={closeMainSettings}
            />
            <OwnerPanel emitOpenEvent={openMainSettings} />
        </div>
    );
}

export default Sidebar;
